Reorganized order of postscripts.

diff --git a/controller/rootimg/install/postscripts/cv_configure_openstack b/controller/rootimg/install/postscripts/cv_configure_openstack
--- a/controller/rootimg/install/postscripts/cv_configure_openstack
+++ b/controller/rootimg/install/postscripts/cv_configure_openstack
@@ -8,35 +8,47 @@
 ##email          : hans.then@clustervision
 
 #--------------------------------------------------------------------------
-# Setup pacemaker
+# Setup galera password and initial databases
 #--------------------------------------------------------------------------
-pcs cluster cib config
-# Setup high availability for the docker containers
-pcs -f config resource create docker systemd:docker op monitor interval="37s"
-pcs -f config resource clone docker clone-node-max=1 notify=false
 
-pcs -f config resource create galera systemd:galera op monitor interval="37s"
-pcs -f config resource clone galera clone-node-max=1 notify=false
+set -x
+systemctl start galera
+systemctl start rabbitmq
+# extract the root password from the galera container
+for i in {300..0}; do
+    password=$(docker exec galera cat /root/.mysql_secret | head -1 | awk '{print $NF}')
+    if docker exec galera mysqladmin -u root -p"${password}" password "system" &> /dev/null; then
+        break
+    fi
+    echo 'MySQL waiting to reset password . . .'
+    sleep 3
+done
+if [[ "$i" = 0 ]]; then
+    echo >&2 'MySQL reset password failed.'
+    exit 1
+fi
 
-pcs -f config resource create rabbitmq systemd:rabbitmq op monitor interval="37s"
-pcs -f config resource create keystone systemd:keystone op monitor interval="37s"
-pcs -f config resource create glance systemd:glance op monitor interval="37s"
-pcs -f config resource create nova-controller systemd:nova-controller op monitor interval="37s"
-
-pcs -f config resource group add grp_OpenStack rabbitmq keystone glance nova-controller
-#pcs -f config resource clone grp_OpenStack clone-node-max=1 notify=false
-
-pcs -f config constraint colocation add grp_OpenStack ip
-pcs -f config constraint order start galera-clone then start grp_OpenStack
-
-pcs cluster cib-push config
-
-#--------------------------------------------------------------------------
-# Create keystone endpoints for glance etc
-#--------------------------------------------------------------------------
+mysql=( mysql --protocol=tcp -uroot -psystem)
+"${mysql[@]}" <<-EOSQL
+    set @@session.sql_log_bin=0;
+    create database keystone;
+    grant all privileges on keystone.* to 'keystone'@'localhost' identified by 'system';
+    grant all privileges on keystone.* to 'keystone'@'%'         identified by 'system';
+    create database glance;
+    grant all privileges on glance.* to 'glance'@'localhost'     identified by 'system';
+    grant all privileges on glance.* to 'glance'@'%'             identified by 'system';
+    create database nova;
+    grant all privileges on nova.* to 'nova'@'localhost'         identified by 'system';
+    grant all privileges on nova.* to 'nova'@'%'                 identified by 'system';
+    create database cinder;
+    grant all privileges on cinder.* to 'cinder'@'localhost'     identified by 'system';
+    grant all privileges on cinder.* to 'cinder'@'%'             identified by 'system';
+    flush privileges ;
+EOSQL
 
 # wait for slapd
 systemctl restart slapd
+systemctl start keystone
 while : ; do
     ldapsearch -H ldap://localhost -x -b dc=local &>/dev/null; [[ $? != 255 ]] && break;
     echo "Waiting for ldap to come up!"
@@ -58,6 +70,9 @@ for i in {300..0}; do
 done
 [[ ${i} == 0 ]] && echo "Timeout waiting for keystone to come up"
 
+systemctl start glance
+systemctl start nova-controller
+
 #read ETH0 ETH1 ETH2 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
 ETH1=$(ip route get 8.8.8.8 | grep -oP 'dev \K\S+')
 ETH2=$(ip route get 10.141.0.0 | grep -oP 'dev \K\S+')
@@ -75,7 +90,6 @@ scp /root/keystonerc_admin controller-2.cluster:/root/keystonerc_admin
 source /root/keystonerc_admin
 
 #-- Create the Flat Network
-systemctl start openstack-nova-network
 
 NETWORK_LABEL="novanetwork"
 nova network-create \
